apiVersion: ENC[AES256_GCM,data:Sn0=,iv:X9h/bXLu8uGoCCLQEpZUZ15prfNF2pMrpupvGTT5ID4=,tag:3mWyQFEWGgacBsymZBUOmg==,type:str]
kind: ENC[AES256_GCM,data:JHkXWMqs,iv:kI3nNEzZSzusLm7tktY9bxscUihDwOahAqZIvc6HviY=,tag:pMcpChdE3u/3UmzxO//jvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:15I0Kq6sUCnoJnA6MmKoz2A=,iv:NgPLZErxU2Fpw/FUA53H6TIQWpqLbkLIYpFezDp4GnA=,tag:egZdi90zpeAq0GN0W4ztHw==,type:str]
    namespace: ENC[AES256_GCM,data:+yO3WfO9A/b3Dg==,iv:/XU2o32flyv8Z0+6v9mSyxt+gyX/xjoXaYHSzved7OI=,tag:8eFQKk6zLUsprEnsW22MQQ==,type:str]
type: ENC[AES256_GCM,data:Fa4OJ/5o,iv:dTrfKlg1FYDMfPQYz3+2x3/wTaRa+zjpxaCHxZoqxCM=,tag:VNmGx7MobaBuEhBfnmvOcQ==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bbFCkhnIg2gP/0f3RzeLVNAv9nM=,iv:1HiBsnBskCFHKR6gDUQL6nrge1AogPmV7y48O39kfC4=,tag:BpSm5KRs3gHM5UoPvxIqbw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:TQSCdl1+vHosvYBC411/qMAiccNpUaid+UEw6UFCyA3oQpaGB2ompQ==,iv:50MWCb0C7OrHEG6GYXlfDtaNn0nlaVHG4AKSHR6wFvc=,tag:xiMgywnr5VDQvYw3vvLKgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaFVFeThoUjVTUzcxMWhM
            d2NzOVRKZzJnQmJDMWFjNUxja3QwMEw5em5zCmxNOWZpT3lsRy92dUYzY0Z6a2RI
            MWlwMml0U2grZkNRRUE4SlhXSWFISUkKLS0tIDEvOGdaZnlvVkhmNGl1ZHY4Z0wv
            U2t0MXRMcm1zNWdFOVpPOXFSZ0xTcWcKqmHEBrrsigBZpfFBlGz52jnv285rD5E9
            6G+TtONji792YWJHQR/fhYgm4VYZ22fwW/vbqu1JjfqLVy96EvJmtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1utn77v4wvgme8ud3cexl82qanpx272g8dqg00dvwdt2v3nkr0vksag3kuh
    lastmodified: "2026-06-19T21:33:35Z"
    mac: ENC[AES256_GCM,data:Q/eQ5TVgsGZCw8wGATYeTxC9Fm4n1dD/8akXWxVUVrgFnpOdq16a97yv1ZH8kiK6Wxdr4FlMXCiK0MbTsi7UE35iwt1oioZ9AbOFky6Uy0KoMmNN4e48fLdJghqh2M6yHOGwTIKpAGJjIC6x7q4qHbed6hbGhYGSW7/r88U1Oi8=,iv:g8zY3Oso2+m833jUqKhk3mbWaRsZfTgisGVUPP2eciQ=,tag:UL3CnXhT8CBaovata+OoWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
