apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: chromadb-pvc
  namespace: chromadb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
