apiVersion: ENC[AES256_GCM,data:lvc=,iv:WPdi1I47SzfZQBEA9wwX4CHfhIj60IL8Sw2AQ7MtbXs=,tag:witE3Gjqq8eFFSss7h/lWQ==,type:str]
kind: ENC[AES256_GCM,data:4YV1Hg7C,iv:eQidgsWoWgdFolvwlx46G9uCfxIQdpfv905gjvKaJ9w=,tag:J3FHjecf4PqRH/SPBrP/mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iURqQQeToJ+tQD+v/pTjEkA=,iv:8UBtKo/MMDuBDCxk567prNDQsogTA0HJFDiDtv9kjTE=,tag:vkImazFBSoHevcuwiuqesg==,type:str]
    namespace: ENC[AES256_GCM,data:yFU+aqlBgLT70rI=,iv:A3z0Nc11KN+wvyn1524wP3L1bvVYIaT7vvsnmqilo6k=,tag:Rx2YdTF2JaJdN0JBJsFA/Q==,type:str]
type: ENC[AES256_GCM,data:2bMk/JKA,iv:XE71ELZMugc//b6CZjY7Ptn+w9J4M9Zalo7O0SvknHM=,tag:XgWST5C2D36421GAgwFRYA==,type:str]
stringData:
    token: ENC[AES256_GCM,data:qxoMdxrXOJO0wwlqgKHZANYbyOs1KJ6EjhvQa/PksJ9+2wZ4/jtRZ+BeiV3ZQyX6Z6QQsHy1/V82hgBA6K1l8+8CqDkQFlOOktn2hJ4iyBSp/k6RXKAqZ7R8nKpKXtHUK9Q7WpADZfzjV1fGZ7kktkufIG8Nd3oo9hkE0lzB3A==,iv:EgUGmhouAwvl64CiQptNUosh2rnrkWR5vIxNtR8cZh4=,tag:upoXTwdpnwhs+Y8z6iFkjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNTN1Uzg1eWI4WXVaK2Fj
            MUhNRkVhem13Q0o0YXYyREtZWk1vcC8yN0FrCk9xMXQzNGlVQ2twMktRVlN2bVkz
            bngyS25VbGFzUU5iM0didWlwN3U0NjAKLS0tIFczSWVxVzZiblNBeXBobEE1V0FU
            QWZRalY3WFJiZ3ZCd2pkTmlLcTlyR2MK0uidd6eajfRdVhseq8kqdqUL97Hd8A5I
            hP643YgucCl1ZBgVBPvw83VItWVwDxKB9GC1y3ohk2+R7nIJgfGI3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1utn77v4wvgme8ud3cexl82qanpx272g8dqg00dvwdt2v3nkr0vksag3kuh
    lastmodified: "2026-06-20T03:28:31Z"
    mac: ENC[AES256_GCM,data:8HqRto29DHAqnyvs6avM1wQ3g4Y0rI946mk2W3gM0anJaKIqS40Z6Z8dMUcI0d3Fo7qL89yE8pfXgGEncLDJnHFUXFgYLZVfcGN2WB83P0gwveMPnsdUhQxzzjIh6LDBV3fXn+gNuild7ve/tuyuws5YSjzpJRFzy575F4KgifA=,iv:jsapChJriAzzZL2/XTootuNqfGiIC6Bp3kKgu32lly4=,tag:hY+8wizq2yZwwopTMf2cqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
